# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-08-29 13:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificate', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useractivatecertificate',
            name='issued_by',
            field=models.CharField(max_length=20, verbose_name='Issued By'),
        ),
    ]
