# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-02-12 12:59
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=200, verbose_name='First Name')),
                ('last_name', models.CharField(max_length=200, verbose_name='Last Name')),
                ('email_id', models.EmailField(max_length=254, unique=True, verbose_name='Email id')),
                ('contact_no', models.CharField(blank=True, max_length=15, unique=True, verbose_name='Contact Numer')),
                ('status', models.BooleanField(choices=[(1, 'Yes'), (0, 'No')], default=1, verbose_name='Status')),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_info', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('messages', models.TextField(verbose_name='Messages')),
                ('read_status', models.BooleanField(choices=[(1, 'Yes'), (0, 'No')], default=1, verbose_name='Read_Status')),
                ('status', models.BooleanField(choices=[(1, 'Yes'), (0, 'No')], default=1, verbose_name='Status')),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_messages', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
